[package]
name = "jazz"
version = "0.1.0"
authors = ["samdoiron <sam.doiron96@gmail.com>"]

[dependencies]
protobuf = "1.2.2"
zmq = "0.8"

[[bin]]
name = "jazz-server"
path = "src/server.rs"

[[bin]]
name = "jazz-client"
path = "src/client.rs"